namespace: {}
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"  # Optional: specify default tag or leave empty for default.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

overrideContainerStartCommand:
  enabled: false
  containerName: nginx-container  # Fixed typo from "ngnix" to "nginx"
  command: []
  args: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

# migration_job:
#   command: [ "/bin/sh" ]
#   args: [ "-c", "/app/batman search-worker /config/*.json" ]
