# Default values for heycoach-helm.

namespace: "heycoach-ns"

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.16.0"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

overrideContainerStartCommand:
  enabled: false
  containerName: "heycoach-container"
  command: []
  args: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  - name: config-volume
    emptyDir: {}

# Removed AWS-related initContainers
