apiVersion: apps/v1
kind: Deployment
metadata:
  #name: {{ include "heycoach-helm.fullname" . }
  name: {{ .Release.Name }}-helm-infra
  #namespace: {{ .Values.namespace }}

  labels:
    app.kubernetes.io/name: {{ include "heycoach-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "heycoach-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "heycoach-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "heycoach-helm.serviceAccountName" . }}
      containers:
        - name: {{ .Values.overrideContainerStartCommand.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          emptyDir: {}
